# In this notebook, we are going to cover some of the most fundamental concepts of Tensors using tensor flow

More specifically, we are going to cover:
* introduction to tensors
* getting information from tensors
* manipulating tensors
* tensors & numpy
* using @tf.function (way to speed up regular python functions)
* using GPUs with tensor flows (or TPUs)
* excersizes to try for yourself

# Introduction to Tensors


In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions of a tensor (ndim = number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check the dimensions of the vector
vector.ndim

1

In [ ]:
# create a matrix (matrix has more than 1 dimension)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# dimensions of matrix
matrix.ndim

2

In [ ]:
# create another matrix 
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]]
                             , dtype = tf.float16) # specify datatype with dtype paramter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# What is the number of dimensions of another_matrix
another_matrix.ndim

2

In [ ]:
# Lets create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor                             

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

# What we have created so far
* Scalar: A single number
* Vector: A number with direction 
* Matrix: a 2 dimensional array of number
* Tensor: an n-dimensional array of numbers (n can be any number, a 0-dimensional tensor is a scalar, 1 dimensional tensor is vector)

Creating Tensors with tf.Variable

In [3]:
# Create the same tensor with tf.Variable() as above

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [6]:
# change elements in changeable tensor (ONLY WORKS WITH .assign)

changeable_tensor[0] = 5 # FAILS
changeable_tensor

TypeError: ignored

In [ ]:
# trying .assign()
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# changing unchangeable tensor  [Doesnt work]
unchangeable_tensor[0].assign(7)
unchangeable_tensor

# Creating random tensors

Random tensors are tensors of some arbitary size which contain random numbers

NOTE: Rarely in practice will you need to decide whether to use tf.constant or tf.Variable to create tensors, as TensorFlow does this for you. However, if in doubt, use tf.constant and change it later if needed

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducability
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42) # set seed for reproducability
random_2 = random_2.normal(shape=(3,2))

#are they equal

random_1, random_2, random_1 == random_2

## Shuffle the order of elements in a tensor

In [ ]:
# shuffle a tensor (valuable for when you want to shuffle your data so the inherit order doesnt effect learning)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])


# shuffle our non-shuffled tensor
# Rule 4: If we want our shuffled tensors to be in the same order, we have got to use the global and operational level random seed
tf.random.set_seed(42) # Global level random seed
tf.random.shuffle(not_shuffled, seed = 42) # Operational level random seed

### other ways to make tensors




In [ ]:
# Create Tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create Tensor of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [ ]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) # create a numpy array between 1 and 25

# X = tf.constant(some_matrix) # Capital for matrix or tensor
# y = tf.constant(vector) # non capital for vector
numpy_A   

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4)) # Tensor , elemnt must give same number of elements in tensor 2 * 3 * 4 = 24
B = tf.constant(numpy_A) # Vector
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors

* Shape = tensor.shape
* Rank  = tensor.ndim
* Axis or dimension = tensor[0] , tensor[:,1]...
* Size = tf.size(tensor)

In [ ]:
# Create rank 4 tensor

rank_4_tensor = tf.zeros(shape=[2,3,4,5])


In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element:",rank_4_tensor.dtype)
print("number of dimensions (rank):", rank_4_tensor.ndim)
print("shape of tensor", rank_4_tensor.shape)
print("Element along the 0 axis:", rank_4_tensor.shape[0])
print("elements along the last axis:", rank_4_tensor.shape[-1])
print("total number of element in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
number of dimensions (rank): 4
shape of tensor (2, 3, 4, 5)
Element along the 0 axis: 2
elements along the last axis: 5
total number of element in our tensor: 120


### Indexing tensors
Tensors can be indexed just like python lists

In [ ]:
some_List = [1,2,3,4]
some_List[:2]

[1, 2]

In [ ]:
# Get the first 2 elements of each dimension 
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
some_List[:1] 

[1]

In [ ]:
# get first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[10,7],[3,4]])

rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get last item of each of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0) # expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

# Manipulating Tensors (Tensor Operations)

**Basic operations**
`+`,`-`,`*`,`/`

In [ ]:
# You can add values to a tensor using the addition operator

tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# multiplication also works
tensor = tensor * 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# We can use the tensorflow built in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1000,  700],
       [ 300,  400]], dtype=int32)>

**Matrix Multiplication**

In Machine learning, matrix multiplication is one of the most common tensor opeartions

In [ ]:
# matrix multiplication in tensor flwo
tensor
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12100,  9800],
       [ 4200,  3700]], dtype=int32)>

In [ ]:
# matrix multiplication with python opearator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12100,  9800],
       [ 4200,  3700]], dtype=int32)>

In [ ]:
tensor.shape


TensorShape([2, 2])

## Changing shape of matrix , transpose is not same as reshape
## transpose flips axis
## reshape shuffles tensor around into shape you want
`tf.transpose(X), tf.reshape(X, shape=(2,3))`

**Dot product**

Matrix multiplication is also reffered to as the dot product
You can perform matrix multiplcation using:
* `tf.matmul`
* `tf.tensordot()`

In [ ]:
# perform the dot product on X and Y (requires X or Y to be transposed)
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

In [ ]:
tf.tensordot(tf.transpose(X),Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Check the values of Y, Reshape Y, and transposed Y
print("normal Y:",Y)
print("\n")
print("reshaped Y to (2,3):",tf.reshape(Y,shape=(2,3)) )
print("\n")
print("transpose Y to (2,3)", tf.transpose(Y))


normal Y: tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


reshaped Y to (2,3): tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


transpose Y to (2,3) tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


### Chaning the data type of a tensor

In [ ]:
# Create a new tensore with default datatype (float 32)
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [ ]:
# Change float 32 to float 16 (reduce precision)
D = tf.cast(B, dtype=tf.float16)
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from Int32 to float 32
E = tf.cast(C, dtype=tf.int16)
E,E.dtype


(<tf.Tensor: shape=(2,), dtype=int16, numpy=array([ 7, 10], dtype=int16)>,
 tf.int16)

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [ ]:
# Get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Get absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets Go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# Create a random tensor with values between 0 and 100 of size 50

E = tf.constant(np.random.randint(0,100,size=50))
E


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([73, 75, 76, 41, 89,  2, 97, 50, 74, 20, 41, 68, 50, 96, 73, 38, 23,
        2, 23, 36, 83, 85, 84, 85, 80,  3, 25, 37, 67, 83, 86, 26, 11, 10,
       33, 27, 45, 27,  8,  4, 15,  0, 90, 18, 85, 52, 87, 54, 14, 80])>

In [ ]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
# Find the mean of a tensor
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [ ]:
# Find the sum of a tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2451>

In [ ]:
# Find the variance of our Tensor
import tensorflow_probability as tfp

tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=958>

In [ ]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.953184>

In [ ]:
# Find the varience of our E tensor
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=958.0996>

### Find the positional maximum and minimum

In [ ]:
# Create a new tensor for finding the positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Index on our Smallest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

### Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One Hot encoding tensors 

In [ ]:
# Create a list of indices
some_list = [0,1,2,3] # Could be red green blue, purple

# one hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo I love deep learning", off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep learning']],
      dtype=object)>

### Squaring, log, square root

In [ ]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# square a tensor
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
## square root a tensor - Will wrror method requires non int dtype
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
# find log of a tensor - Will wrror method requires non int dtype
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tesnors and NumPy

Tensorflow interacts beautifully with Numpy arrays.

In [ ]:
# Create a tensor directly from a NumPy Array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert tensor back to numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Convert tensor J into numpy array 
J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [ ]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

# Check dtype of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

# Regression Problems - Predicting a number (statistical analysis)
Estimating relationship between dependant variable and one or more independant variable

Example: How much or How many
* How much will my house sell for
* How many people will buy this app
* How much should I save each week for fuel

Inputs and outputs of regression:
Example: Predicting sale price of house

Inputs / Input features (Numerical encoding):
* Number of bedrooms, bathrooms etc. (Indipendant variable)
* Sale price of other house nearby

Outputs:
* Sale Price